apiVersion: v1
kind: Service
metadata:
  name: {{ include "famf.fullname" . }}-frontend
  labels:
    {{- include "famf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "famf.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "famf.fullname" . }}-backend
  labels:
    {{- include "famf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "famf.selectorLabels" . | nindent 4 }}
